version: "3.3"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
volumes:
    redis_data: